version: '3'

services: 

    mysql:
        image: mariadb:${MYSQL_VERSION}
        container_name: mysql
        ports:
            - 3306:3306
        environment:
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_USER: ${MYSQL_USER}
            MYSQL_PASSWORD: ${MYSQL_PASSWORD}
        volumes: 
            - ./data/data_mariadb10:/var/lib/mysql
        restart: unless-stopped
        networks: 
            - scinetwork

    sci-web:
        image: pjaun/apache-php7
        container_name: sci-web
        ports:
            - 80:80
        volumes:  
            - ./www:/var/www/html
        depends_on: 
            - mysql
        restart: unless-stopped
        networks: 
            - scinetwork
    

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        ports:
            - 81:80
        depends_on: 
            - mysql
        environment: 
            - PMA_ARBITRARY=0
            - PMA_HOST=${MYSQL_HOST}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}

        restart: unless-stopped
        links: 
            - mysql
        networks: 
            - scinetwork
networks:
    scinetwork: #name of our shared network that containers will use

